### ISSUE TITLE
scan in background

### ISSUE THREAD

**Issue by darwin2k** [omergul123/Discovery#14]
Hi, great work!
Short question: Is it even possible to scan for a device in background. Or in other words: Is it possible to exchange data("String") between two devices which are both in locked background mode.

Best!

**Comment by omergul** [comment]
@darwin2k Well that's a bit hard (maybe impossible, I haven't tried hard yet). When the scanner is at background, the following delegate isn't called multiple times, it is only called only once when the device is discovered. So we can not continuously receive the rssi number to detect its distance.
- (void)centralManager:(CBCentralManager *)central
  didDiscoverPeripheral:(CBPeripheral *)peripheral
     advertisementData:(NSDictionary *)advertisementData
                  RSSI:(NSNumber *)RSSI

**Comment by darwin2k** [comment]
@omergul123  for me single time recognition when the device enters range is relevant. For my use-case I don´t really need to detect the distance between the devices. I will try this out.  thanks!
