### ISSUE TITLE
It does not show other people nearby

### ISSUE THREAD

**Issue by realexhub** [omergul123/Discovery#23]
Hello, i've compiled and installed the app in two iphone 5 with 8.1 installed , but when i run it and put the username in form, but don't show  the people nearby. How it's possibile ? it dosen't work anymore?

Another question, theoretically it is possible ti implement this in android ? or the bluetooth signal search only ios device?

Thanks 

Alex

**Comment by tmandry** [comment]
I also haven't been able to discover anyone nearby, testing with 3 different devices (iPhone 5, 6, and 6 Plus) and none of them can see each other. Were you able to get this working eventually?

**Comment by tmandry** [comment]
Opened #25
