### ISSUE TITLE
multiple instances of discovery

### ISSUE THREAD

**Issue by yonahforst** [omergul123/Discovery#9]
Hey @omergul123 , Great library! I've been grappling with iBeacon (and trying to simulate it using CB) so looking forward to trying this out. Quick question: Do you see any issue with using multiple instances of discovery within the same app? i.e. one instance to discover nearby devices and multiple other instances advertising?

**Comment by omergul** [comment]
I haven't tried it, have you? But it could drain the battery I suppose. @joshblour

**Comment by yonahforst** [comment]
I did try it but I was getting spotty results. So I ended up with just one instance of each and a broadcast queue for different uuids.
